# Tek satır for döngüsü (One-liner for)


In [2]:
kelime = 'Python'
harf_listesi = []

for harf in kelime:
  harf_listesi.append(harf)

print(harf_listesi)

['P', 'y', 't', 'h', 'o', 'n']


In [0]:
harf_listesi = [harf for harf in 'Python']

# Tek satır if (One-liner if)

In [0]:
# Tek satır if (One-liner if)

kosul = True

if kosul : 
  kelime = 'Elma'
else:
  kelime = 'Armut'

In [0]:
kelime = 'Elma' if kosul else 'Armut'

# Tek satır fonksiyon Lambda (One-liner function Lambda)

In [8]:
kare_al = lambda x: x**2
kare_al(5)

25

#map, reduce, filter, zip fonksiyonları

In [10]:
sayilar = [1, 2, 3, 4, 5, 6, 7]
sayilarin_kareleri = []

for sayi in sayilar:
  sayilarin_kareleri.append(kare_al(sayi))
print(sayilarin_kareleri)

[1, 4, 9, 16, 25, 36, 49]


In [15]:
sayilarin_kareleri = map(kare_al, sayilar)
print(sayilarin_kareleri)

for sayi in sayilarin_kareleri:
  print(sayi)

1
4
9
16
25
36
49


In [17]:
from functools import reduce

sayilar = [1, 6, 3, 7, 10, 0]
print(reduce(lambda x,y: x if x > y else y, sayilar))

# sayılar listesindeki en büyük sayıyı bulmaya çalışıyoruz.

10
10


In [12]:
def besten_uzun(kelime):
  if len(kelime) > 5:
    return True
  else:
    return False
  
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']
uzun_isimler = filter(besten_uzun, isimler)
for isim in uzun_isimler:
  print(isim)

sayilar = [0, 1, 2, 3, 4, 5]

Necati
Mehmet


In [16]:
sayilar = [0, 1, 2, 3, 4, 5]
isimler = ['Oğuz', 'Ahmet', 'Necati', 'Ali', 'Mehmet', 'Ziya']

for i in range(len(sayilar)): 
  print(sayilar[i], isimler[i])

for i in zip(sayilar, isimler):
  print(i)
  #Demet şeklinde

0 Oğuz
1 Ahmet
2 Necati
3 Ali
4 Mehmet
5 Ziya
(0, 'Oğuz')
(1, 'Ahmet')
(2, 'Necati')
(3, 'Ali')
(4, 'Mehmet')
(5, 'Ziya')


# Assert anahtar kelimesi ( Assert keyword )

In [19]:
yas = input("Yaşınız : ")
assert int(yas) >= 0, "Yaşınız negatif olamaz."

Yaşınız : 16


# Üreteçler (Generators)

In [2]:
#Her generator fonksiyonu çağırdığımızda bize farklı birşey veriyor.
def generator():
  i = 1 
  print('Öncelikle bu basıldı.')
  yield i

  i+=1
  print('Sonra bu')
  yield i

  #Bu fonk iki defa çalışacak.

for eleman in generator():
  print("For döngüsü içinde : ", eleman)
#print(next())

Öncelikle bu basıldı.
For döngüsü içinde :  1
Sonra bu
For döngüsü içinde :  2


In [3]:
a = 5

def outer():
  a = 3
  def inner():
    nonlocal a #nonlocal fonksiyonu dışarıdaki a değerimizi değiştirir
    a += 5 
    print("inner fonksiyon : ", a)
  print("outer fonksiyon:", a)
  return inner()

outer()
print("global : ",a)

outer fonksiyon: 3
inner fonksiyon :  8
global :  5


#Decorators

In [11]:
from datetime import datetime

def show_time(func):
  def wrapper():
    print("Time : ", datetime.now().time())
    func()
  return wrapper

@show_time
def say_hi():
  print("Hi")

@show_time
def say_bye():
  print('Bye')

say_hi()
say_bye()

Time :  12:32:54.158066
Hi
Time :  12:32:54.158214
Bye


#Numpy

In [0]:
import numpy as np 

In [14]:
a = np.array([10, 20, 30, 40, 50, 60])
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(6,)


In [15]:
a[2]

30

In [18]:
a[2] *= 8
print(a[2])

240


In [22]:
b = np.array([
              [10,20,30],
              [40,50,60]
              ])
print(b)
print(b.shape)
print(b.dtype) #numpy arrayin içinde hangi tip eleman var?

[[10 20 30]
 [40 50 60]]
(2, 3)
int64


In [23]:
a = np.array([10, 20, 30, 40, 50, 60])
np.sin(a)


array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485,
       -0.30481062])

In [24]:
np.cos(a)

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603,
       -0.95241298])

In [25]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456])

In [26]:
np.exp(a)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26])

In [27]:
np.max(a)

60

In [28]:
np.min(a)

10

In [29]:
np.argmax(a) #max değerin hangi indekste ona bakıyorum.

5

In [30]:
np.mean(a)

35.0

In [31]:
np.median(a)

35.0

In [32]:
np.std(a)

17.07825127659933

In [33]:
#axis = 1 == Row
#axis = 0 == Column
np.sum(b, axis=1)

array([ 60, 150])

In [34]:
zeros = np.zeros((3,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
ones = np.ones((3, 3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
full = np.full((3, 3), 5)
print(full)



[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [38]:
eye = np.eye(5)
print(eye)
#5x5 lik birim matris oluşturur.

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
arange = np.arange(7)
print(arange)

arange = np.arange(0, 10, 2)
print(arange)

[0 1 2 3 4 5 6]
[0 2 4 6 8]


In [48]:
#Create randint
random = np.random.random((3,3)) #float
print(random)

[[0.63329925 0.51601747 0.40820085]
 [0.9523911  0.35462563 0.01458484]
 [0.87040274 0.74144941 0.60155613]]


In [45]:
arr = np.random.randint(20, size = (5,5)) #integer
print(arr)

[[10  9  9  2  0]
 [12  7 10 17  5]
 [13  3  2  7  1]
 [19 14 12  7 12]
 [12  1  0  4  9]]


In [49]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [50]:
eye*6

array([[6., 0., 0., 0., 0.],
       [0., 6., 0., 0., 0.],
       [0., 0., 6., 0., 0.],
       [0., 0., 0., 6., 0.],
       [0., 0., 0., 0., 6.]])

In [59]:
print(arr)
print("3.satır 2.sütundaki eleman : ",arr[2, 1]) #indeksleme arr[erişmek istenen satır, erişmek istenen sütun]

[[10  9  9  2  0]
 [12  7 10 17  5]
 [13  3  2  7  1]
 [19 14 12  7 12]
 [12  1  0  4  9]]
3.satır 2.sütundaki eleman :  3


In [62]:
arr[0:3,::]

array([[10,  9,  9,  2,  0],
       [12,  7, 10, 17,  5],
       [13,  3,  2,  7,  1]])

In [67]:
arr == 4
arr[arr == 4]
arr[arr > 10]

array([12, 17, 13, 19, 14, 12, 12, 12])

In [64]:
np.where(arr==4)

(array([4]), array([3]))

In [75]:
np.array([
          [1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12]
]).reshape(3,-1).shape

(3, 4)

In [70]:
c = np.random.randint(10, size=(3,3))
print(c)
c_inv = np.linalg.inv(c)
print(c_inv)

[[7 7 5]
 [6 0 9]
 [5 1 6]]
[[-0.3        -1.23333333  2.1       ]
 [ 0.3         0.56666667 -1.1       ]
 [ 0.2         0.93333333 -1.4       ]]


# İç Çarpım (Dot Product)

In [88]:
 a = np.array([
               [1,2,3],
               [4,5,6]
               ])
 print(a.shape)


(2, 3)


In [89]:
b = np.array([
              [7, 8, 9],
              [10, 11, 12]
])
print(a.shape)

(2, 3)


In [90]:
axb = np.dot(a, b) #Soldaki çarpılan matrisin sütunu sağdaki çarpılan matrisin satır sayısına eşit olmalı


ValueError: ignored

In [91]:
(b.T).shape # Transpose

(3, 2)

In [0]:
axb = np.dot(a, b.T)

In [93]:
print(axb)
print(axb.shape)

[[ 50  68]
 [122 167]]
(2, 2)
